### ISSUE TITLE
Request S:heartCanisterBaubleType=ANY

### ISSUE THREAD

**Issue by raziel23x** [Radient-Sora/Baubley-Heart-Canisters#10]
is there any way you can make this
S:heartCanisterBaubleType=ANY
as a config issue as i only see

    # What Type of Bauble is the Heart Amulet?
    # Valid values:
    # AMULET
    # RING
    # BELT
    # TRINKET
    # HEAD
    # BODY
    # CHARM
    S:heartCanisterBaubleType=AMULET

**Comment by Radient-Sora** [comment]
TRINKET is the same as ALL thats code done by baubles

-sorry for late response
