### ISSUE TITLE
[1.12.2] no signature 

### ISSUE THREAD

**Issue by NickelHub** [Radient-Sora/Baubley-Heart-Canisters#13]
I always got this in my console while starting the game.

[K[31;1m[09:05:35] [Server thread/ERROR] [FML]: The mod bhc is expecting signature undefined for source baubley-heart-canisters-1.12.2-1.2.1.jar, however there is no signature matching that description

**Comment by Radient-Sora** [comment]
Its nothing to worry about its for fingerprinting Upcraft added it but don't be alarmed

**Comment by NickelHub** [comment]
Could this be closed then?

**Comment by UpcraftLP** [comment]
Tbh you should finally set up jar signing @Radient-Sora :p
