### ISSUE TITLE
resourcepack hearts

### ISSUE THREAD

**Issue by MeinKraft** [Radient-Sora/Baubley-Heart-Canisters#14]
Hi, Im using Faithful32 modded texture pack. And Im trying to add a 32px texture for your HUD Heart image, but Im having trouble finding it in your mod?

is there a HUD Heart image or is it hard-coded?  could it be possible to re-colour any heart image from the Minecraft:Textures:gui:Icons.png file?  so that it remains compatible with any resourcepack?

just a thought, thank you

**Comment by UpcraftLP** [comment]
The recolored health bars are from mantle, not baubley heart canisters
