### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bookerthegeek** [Radient-Sora/Baubley-Heart-Canisters#16]
# Heyo
Love the mod. Quick request though. Would you be able to add a `NULL` option to where the CanisterBaubleType can go? Just so that I can do the following:
- `S:blueCanisterBaubleType=NULL`
- `S:greenCanisterBaubleType=NULL`
- `orangeCanisterBaubleType=NULL`
- `S:redCanisterBaubleType=NULL`

This way so I can require people to use the heart Canister Bauble instead of using the individual heart canisters.

**Comment by Radient-Sora** [comment]
I will see about an update for this feature just give me time I have been very busy with other projects try to understand

**Comment by bookerthegeek** [comment]
Of course! Take your time and I appreciate the fact that youve made this mod at all. :) Pressure from me is something you'll not receive. I'd rather you take your time then rush.

.... Are those other prijects MC related?

**Comment by Radient-Sora** [comment]
Yes also if you get the latest version of the mod I added your feature it just works differently as BaubleType can't be NULL
