### ISSUE TITLE
Parsing error loading recipe

### ISSUE THREAD

**Issue by bookerthegeek** [Radient-Sora/Baubley-Heart-Canisters#17]
# Heyo!
Tis me again.... Saw [this](https://gist.github.com/bookerthegeek/0fa9e91ea38c22727516eb85b98a7f5a) in my server log and thought you would want to know. Keep up the great work.

[Mod List](https://gist.github.com/bookerthegeek/a0f0b398fe9563af2a6e6ffc3cb87444)

**Comment by Radient-Sora** [comment]
LUL i borked the dummy recipe the normal should work though will push an update out later today thanks lol
