### ISSUE TITLE
[Solved] Adding your own mobs to BHC heart drops from other mods crashes the game/server

### ISSUE THREAD

**Issue by MushWolf** [Radient-Sora/Baubley-Heart-Canisters#24]
It looks like the game can't identify a non-vanilla mob. I've tried mobs from all the ones in the attached config file (changed it to a .txt cause github is being iffy about .json).

[bhc-drops.txt](https://github.com/Radient-Sora/Baubley-Heart-Canisters/files/3069652/bhc-drops.txt)

Also attached a crash log.

[crash-2019-04-11_18.25.22-client.txt](https://github.com/Radient-Sora/Baubley-Heart-Canisters/files/3069647/crash-2019-04-11_18.25.22-client.txt)

Maybe if it's not intended to work with non-vanilla mobs, you could maybe make it work with non-vanilla ones? :D

**Comment by Radient-Sora** [comment]
That's not a valid Json you sent ...try adding commas

**Comment by MushWolf** [comment]
Ah. Well sorry to bother you. That did fix it. There were no comma's in the original file and I'm not versed enough in config editing/JSON-ing to realize it needed comma's :D 

Consider the issue closed. But maybe leave it for people with the same issue/question 👍 

Anybody reading this. You need to add comma's after each entity you add :D

**Comment by Radient-Sora** [comment]
No it's perfectly fine the bug scared me for like a brief sec then i lol'd a lil when I saw the JSON it's easy once you learn it lol good luck and lemme know if you find anymore bugs.
