### ISSUE TITLE
Setting a stack limit allows to equip the same typ of heart into every slot and still gives hearts

### ISSUE THREAD

**Issue by zEpiixz** [Radient-Sora/Baubley-Heart-Canisters#7]
I think it shouldnt be that if you set a heart stack limit you can eq the same type of heart into everyslot and still gives the hearts. Which makes the other heart  types useless. 
https://imgur.com/TaGqdth

**Comment by Radient-Sora** [comment]
So the way the stacks for each heart type works is it adds a modifer for each stack if mantle was not on the pack the hearts would be placed above each other as each is an individual modifer... Meaning blue hearts are the same as red hearts if you set the max stack size to 5 you can have 15 hearts equiped (3 stacks of 5) you would only get 5 extra hearts you would need to place the next tier for it to increase further

**Comment by Radient-Sora** [comment]
Due to the way BaublesType.TRINKET works it's very very difficult to check each slot type and see it's values I can make a config that let's you set the Bauble Type for each Heart Type
